# Generated by Django 4.1.5 on 2023-02-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(default='', max_length=30),
        ),
    ]
